#ifndef LANG_CODE_DEFINE
#define LANG_CODE_DEFINE(alpha_three, alpha_two, name)
#endif
#ifndef LANG_CODE_LAST_DEFINE
#define LANG_CODE_LAST_DEFINE(alpha_three, alpha_two, name)
#endif

LANG_CODE_DEFINE("aar", "aa", "Afar")
LANG_CODE_DEFINE("abk", "ab", "Abkhazian")
LANG_CODE_DEFINE("afr", "af", "Afrikaans")
LANG_CODE_DEFINE("aka", "ak", "Akan")
LANG_CODE_DEFINE("alb", "sq", "Albanian")
LANG_CODE_DEFINE("amh", "am", "Amharic")
LANG_CODE_DEFINE("ara", "ar", "Arabic")
LANG_CODE_DEFINE("arg", "an", "Aragonese")
LANG_CODE_DEFINE("arm", "hy", "Armenian")
LANG_CODE_DEFINE("asm", "as", "Assamese")
LANG_CODE_DEFINE("ava", "av", "Avaric")
LANG_CODE_DEFINE("ave", "ae", "Avestan")
LANG_CODE_DEFINE("aym", "ay", "Aymara")
LANG_CODE_DEFINE("aze", "az", "Azerbaijani")
LANG_CODE_DEFINE("bak", "ba", "Bashkir")
LANG_CODE_DEFINE("bam", "bm", "Bambara")
LANG_CODE_DEFINE("baq", "eu", "Basque")
LANG_CODE_DEFINE("bel", "be", "Belarusian")
LANG_CODE_DEFINE("ben", "bn", "Bengali")
LANG_CODE_DEFINE("bih", "bh", "Bihari languages")
LANG_CODE_DEFINE("bis", "bi", "Bislama")
LANG_CODE_DEFINE("bos", "bs", "Bosnian")
LANG_CODE_DEFINE("bre", "br", "Breton")
LANG_CODE_DEFINE("bul", "bg", "Bulgarian")
LANG_CODE_DEFINE("bur", "my", "Burmese")
LANG_CODE_DEFINE("cat", "ca", "Catalan; Valencian")
LANG_CODE_DEFINE("cha", "ch", "Chamorro")
LANG_CODE_DEFINE("che", "ce", "Chechen")
LANG_CODE_DEFINE("chi", "zh", "Chinese")
LANG_CODE_DEFINE("chu", "cu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic")
LANG_CODE_DEFINE("chv", "cv", "Chuvash")
LANG_CODE_DEFINE("cor", "kw", "Cornish")
LANG_CODE_DEFINE("cos", "co", "Corsican")
LANG_CODE_DEFINE("cre", "cr", "Cree")
LANG_CODE_DEFINE("cze", "cs", "Czech")
LANG_CODE_DEFINE("dan", "da", "Danish")
LANG_CODE_DEFINE("div", "dv", "Divehi; Dhivehi; Maldivian")
LANG_CODE_DEFINE("dut", "nl", "Dutch; Flemish")
LANG_CODE_DEFINE("dzo", "dz", "Dzongkha")
LANG_CODE_DEFINE("eng", "en", "English")
LANG_CODE_DEFINE("epo", "eo", "Esperanto")
LANG_CODE_DEFINE("est", "et", "Estonian")
LANG_CODE_DEFINE("ewe", "ee", "Ewe")
LANG_CODE_DEFINE("fao", "fo", "Faroese")
LANG_CODE_DEFINE("fij", "fj", "Fijian")
LANG_CODE_DEFINE("fin", "fi", "Finnish")
LANG_CODE_DEFINE("fre", "fr", "French")
LANG_CODE_DEFINE("fry", "fy", "Western Frisian")
LANG_CODE_DEFINE("ful", "ff", "Fulah")
LANG_CODE_DEFINE("geo", "ka", "Georgian")
LANG_CODE_DEFINE("ger", "de", "German")
LANG_CODE_DEFINE("gla", "gd", "Gaelic; Scottish Gaelic")
LANG_CODE_DEFINE("gle", "ga", "Irish")
LANG_CODE_DEFINE("glg", "gl", "Galician")
LANG_CODE_DEFINE("glv", "gv", "Manx")
LANG_CODE_DEFINE("gre", "el", "Greek, Modern (1453-)")
LANG_CODE_DEFINE("grn", "gn", "Guarani")
LANG_CODE_DEFINE("guj", "gu", "Gujarati")
LANG_CODE_DEFINE("hat", "ht", "Haitian; Haitian Creole")
LANG_CODE_DEFINE("hau", "ha", "Hausa")
LANG_CODE_DEFINE("heb", "he", "Hebrew")
LANG_CODE_DEFINE("her", "hz", "Herero")
LANG_CODE_DEFINE("hin", "hi", "Hindi")
LANG_CODE_DEFINE("hmo", "ho", "Hiri Motu")
LANG_CODE_DEFINE("hrv", "hr", "Croatian")
LANG_CODE_DEFINE("hun", "hu", "Hungarian")
LANG_CODE_DEFINE("ibo", "ig", "Igbo")
LANG_CODE_DEFINE("ice", "is", "Icelandic")
LANG_CODE_DEFINE("ido", "io", "Ido")
LANG_CODE_DEFINE("iii", "ii", "Sichuan Yi; Nuosu")
LANG_CODE_DEFINE("iku", "iu", "Inuktitut")
LANG_CODE_DEFINE("ile", "ie", "Interlingue; Occidental")
LANG_CODE_DEFINE("ina", "ia", "Interlingua (International Auxiliary Language Association)")
LANG_CODE_DEFINE("ind", "id", "Indonesian")
LANG_CODE_DEFINE("ipk", "ik", "Inupiaq")
LANG_CODE_DEFINE("ita", "it", "Italian")
LANG_CODE_DEFINE("jav", "jv", "Javanese")
LANG_CODE_DEFINE("jpn", "ja", "Japanese")
LANG_CODE_DEFINE("kal", "kl", "Kalaallisut; Greenlandic")
LANG_CODE_DEFINE("kan", "kn", "Kannada")
LANG_CODE_DEFINE("kas", "ks", "Kashmiri")
LANG_CODE_DEFINE("kau", "kr", "Kanuri")
LANG_CODE_DEFINE("kaz", "kk", "Kazakh")
LANG_CODE_DEFINE("khm", "km", "Central Khmer")
LANG_CODE_DEFINE("kik", "ki", "Kikuyu; Gikuyu")
LANG_CODE_DEFINE("kin", "rw", "Kinyarwanda")
LANG_CODE_DEFINE("kir", "ky", "Kirghiz; Kyrgyz")
LANG_CODE_DEFINE("kom", "kv", "Komi")
LANG_CODE_DEFINE("kon", "kg", "Kongo")
LANG_CODE_DEFINE("kor", "ko", "Korean")
LANG_CODE_DEFINE("kua", "kj", "Kuanyama; Kwanyama")
LANG_CODE_DEFINE("kur", "ku", "Kurdish")
LANG_CODE_DEFINE("lao", "lo", "Lao")
LANG_CODE_DEFINE("lat", "la", "Latin")
LANG_CODE_DEFINE("lav", "lv", "Latvian")
LANG_CODE_DEFINE("lim", "li", "Limburgan; Limburger; Limburgish")
LANG_CODE_DEFINE("lin", "ln", "Lingala")
LANG_CODE_DEFINE("lit", "lt", "Lithuanian")
LANG_CODE_DEFINE("ltz", "lb", "Luxembourgish; Letzeburgesch")
LANG_CODE_DEFINE("lub", "lu", "Luba-Katanga")
LANG_CODE_DEFINE("lug", "lg", "Ganda")
LANG_CODE_DEFINE("mac", "mk", "Macedonian")
LANG_CODE_DEFINE("mah", "mh", "Marshallese")
LANG_CODE_DEFINE("mal", "ml", "Malayalam")
LANG_CODE_DEFINE("mao", "mi", "Maori")
LANG_CODE_DEFINE("mar", "mr", "Marathi")
LANG_CODE_DEFINE("may", "ms", "Malay")
LANG_CODE_DEFINE("mlg", "mg", "Malagasy")
LANG_CODE_DEFINE("mlt", "mt", "Maltese")
LANG_CODE_DEFINE("mon", "mn", "Mongolian")
LANG_CODE_DEFINE("nau", "na", "Nauru")
LANG_CODE_DEFINE("nav", "nv", "Navajo; Navaho")
LANG_CODE_DEFINE("nbl", "nr", "Ndebele, South; South Ndebele")
LANG_CODE_DEFINE("nde", "nd", "Ndebele, North; North Ndebele")
LANG_CODE_DEFINE("ndo", "ng", "Ndonga")
LANG_CODE_DEFINE("nep", "ne", "Nepali")
LANG_CODE_DEFINE("nno", "nn", "Norwegian Nynorsk; Nynorsk, Norwegian")
LANG_CODE_DEFINE("nob", "nb", "Bokmål, Norwegian; Norwegian Bokmål")
LANG_CODE_DEFINE("nor", "no", "Norwegian")
LANG_CODE_DEFINE("nya", "ny", "Chichewa; Chewa; Nyanja")
LANG_CODE_DEFINE("oci", "oc", "Occitan (post 1500); Provençal")
LANG_CODE_DEFINE("oji", "oj", "Ojibwa")
LANG_CODE_DEFINE("ori", "or", "Oriya")
LANG_CODE_DEFINE("orm", "om", "Oromo")
LANG_CODE_DEFINE("oss", "os", "Ossetian; Ossetic")
LANG_CODE_DEFINE("pan", "pa", "Panjabi; Punjabi")
LANG_CODE_DEFINE("per", "fa", "Persian")
LANG_CODE_DEFINE("pli", "pi", "Pali")
LANG_CODE_DEFINE("pol", "pl", "Polish")
LANG_CODE_DEFINE("por", "pt", "Portuguese")
LANG_CODE_DEFINE("pus", "ps", "Pushto; Pashto")
LANG_CODE_DEFINE("que", "qu", "Quechua")
LANG_CODE_DEFINE("roh", "rm", "Romansh")
LANG_CODE_DEFINE("rum", "ro", "Romanian; Moldavian; Moldovan")
LANG_CODE_DEFINE("run", "rn", "Rundi")
LANG_CODE_DEFINE("rus", "ru", "Russian")
LANG_CODE_DEFINE("sag", "sg", "Sango")
LANG_CODE_DEFINE("san", "sa", "Sanskrit")
LANG_CODE_DEFINE("sin", "si", "Sinhala; Sinhalese")
LANG_CODE_DEFINE("slo", "sk", "Slovak")
LANG_CODE_DEFINE("slv", "sl", "Slovenian")
LANG_CODE_DEFINE("sme", "se", "Northern Sami")
LANG_CODE_DEFINE("smo", "sm", "Samoan")
LANG_CODE_DEFINE("sna", "sn", "Shona")
LANG_CODE_DEFINE("snd", "sd", "Sindhi")
LANG_CODE_DEFINE("som", "so", "Somali")
LANG_CODE_DEFINE("sot", "st", "Sotho, Southern")
LANG_CODE_DEFINE("spa", "es", "Spanish; Castilian")
LANG_CODE_DEFINE("srd", "sc", "Sardinian")
LANG_CODE_DEFINE("srp", "sr", "Serbian")
LANG_CODE_DEFINE("ssw", "ss", "Swati")
LANG_CODE_DEFINE("sun", "su", "Sundanese")
LANG_CODE_DEFINE("swa", "sw", "Swahili")
LANG_CODE_DEFINE("swe", "sv", "Swedish")
LANG_CODE_DEFINE("tah", "ty", "Tahitian")
LANG_CODE_DEFINE("tam", "ta", "Tamil")
LANG_CODE_DEFINE("tat", "tt", "Tatar")
LANG_CODE_DEFINE("tel", "te", "Telugu")
LANG_CODE_DEFINE("tgk", "tg", "Tajik")
LANG_CODE_DEFINE("tgl", "tl", "Tagalog")
LANG_CODE_DEFINE("tha", "th", "Thai")
LANG_CODE_DEFINE("tib", "bo", "Tibetan")
LANG_CODE_DEFINE("tir", "ti", "Tigrinya")
LANG_CODE_DEFINE("ton", "to", "Tonga (Tonga Islands)")
LANG_CODE_DEFINE("tsn", "tn", "Tswana")
LANG_CODE_DEFINE("tso", "ts", "Tsonga")
LANG_CODE_DEFINE("tuk", "tk", "Turkmen")
LANG_CODE_DEFINE("tur", "tr", "Turkish")
LANG_CODE_DEFINE("twi", "tw", "Twi")
LANG_CODE_DEFINE("uig", "ug", "Uighur; Uyghur")
LANG_CODE_DEFINE("ukr", "uk", "Ukrainian")
LANG_CODE_DEFINE("urd", "ur", "Urdu")
LANG_CODE_DEFINE("uzb", "uz", "Uzbek")
LANG_CODE_DEFINE("ven", "ve", "Venda")
LANG_CODE_DEFINE("vie", "vi", "Vietnamese")
LANG_CODE_DEFINE("vol", "vo", "Volapük")
LANG_CODE_DEFINE("wel", "cy", "Welsh")
LANG_CODE_DEFINE("wln", "wa", "Walloon")
LANG_CODE_DEFINE("wol", "wo", "Wolof")
LANG_CODE_DEFINE("xho", "xh", "Xhosa")
LANG_CODE_DEFINE("yid", "yi", "Yiddish")
LANG_CODE_DEFINE("yor", "yo", "Yoruba")
LANG_CODE_DEFINE("zha", "za", "Zhuang; Chuang")
LANG_CODE_LAST_DEFINE("zul", "zu", "Zulu")

#undef LANG_CODE_DEFINE
#undef LANG_CODE_LAST_DEFINE
