#include <algorithm>
#include <cstring>
#include <vector>
#include <iostream>
#include "langcode.h"
#include <cstring>
#include <cstdlib>
#include <stdexcept>

using namespace std;
using namespace qmx;

void throw_assertion(const char* msg, int line) {
    char error[512] = {0};
    sprintf(error, "exception on line %d with condition %s", line, msg);
    throw std::runtime_error(error);
}

#define CHECK(cond) if (!(cond)) throw_assertion(#cond, __LINE__)


static void test_lang_code_old() {
    CHECK(strcmp("aar", langcode_three_old("aa")) == 0);
    CHECK(strcmp("abk", langcode_three_old("ab")) == 0);
    CHECK(strcmp("afr", langcode_three_old("af")) == 0);
    CHECK(strcmp("aka", langcode_three_old("ak")) == 0);
    CHECK(strcmp("alb", langcode_three_old("sq")) == 0);
    CHECK(strcmp("amh", langcode_three_old("am")) == 0);
    CHECK(strcmp("ara", langcode_three_old("ar")) == 0);
    CHECK(strcmp("arg", langcode_three_old("an")) == 0);
    CHECK(strcmp("arm", langcode_three_old("hy")) == 0);
    CHECK(strcmp("asm", langcode_three_old("as")) == 0);
    CHECK(strcmp("ava", langcode_three_old("av")) == 0);
    CHECK(strcmp("ave", langcode_three_old("ae")) == 0);
    CHECK(strcmp("aym", langcode_three_old("ay")) == 0);
    CHECK(strcmp("aze", langcode_three_old("az")) == 0);
    CHECK(strcmp("bak", langcode_three_old("ba")) == 0);
    CHECK(strcmp("bam", langcode_three_old("bm")) == 0);
    CHECK(strcmp("baq", langcode_three_old("eu")) == 0);
    CHECK(strcmp("bel", langcode_three_old("be")) == 0);
    CHECK(strcmp("ben", langcode_three_old("bn")) == 0);
    CHECK(strcmp("bih", langcode_three_old("bh")) == 0);
    CHECK(strcmp("bis", langcode_three_old("bi")) == 0);
    CHECK(strcmp("bos", langcode_three_old("bs")) == 0);
    CHECK(strcmp("bre", langcode_three_old("br")) == 0);
    CHECK(strcmp("bul", langcode_three_old("bg")) == 0);
    CHECK(strcmp("bur", langcode_three_old("my")) == 0);
    CHECK(strcmp("cat", langcode_three_old("ca")) == 0);
    CHECK(strcmp("cha", langcode_three_old("ch")) == 0);
    CHECK(strcmp("che", langcode_three_old("ce")) == 0);
    CHECK(strcmp("chi", langcode_three_old("zh")) == 0);
    CHECK(strcmp("chu", langcode_three_old("cu")) == 0);
    CHECK(strcmp("chv", langcode_three_old("cv")) == 0);
    CHECK(strcmp("cor", langcode_three_old("kw")) == 0);
    CHECK(strcmp("cos", langcode_three_old("co")) == 0);
    CHECK(strcmp("cre", langcode_three_old("cr")) == 0);
    CHECK(strcmp("cze", langcode_three_old("cs")) == 0);
    CHECK(strcmp("dan", langcode_three_old("da")) == 0);
    CHECK(strcmp("div", langcode_three_old("dv")) == 0);
    CHECK(strcmp("dut", langcode_three_old("nl")) == 0);
    CHECK(strcmp("dzo", langcode_three_old("dz")) == 0);
    CHECK(strcmp("eng", langcode_three_old("en")) == 0);
    CHECK(strcmp("epo", langcode_three_old("eo")) == 0);
    CHECK(strcmp("est", langcode_three_old("et")) == 0);
    CHECK(strcmp("ewe", langcode_three_old("ee")) == 0);
    CHECK(strcmp("fao", langcode_three_old("fo")) == 0);
    CHECK(strcmp("fij", langcode_three_old("fj")) == 0);
    CHECK(strcmp("fin", langcode_three_old("fi")) == 0);
    CHECK(strcmp("fre", langcode_three_old("fr")) == 0);
    CHECK(strcmp("fry", langcode_three_old("fy")) == 0);
    CHECK(strcmp("ful", langcode_three_old("ff")) == 0);
    CHECK(strcmp("geo", langcode_three_old("ka")) == 0);
    CHECK(strcmp("ger", langcode_three_old("de")) == 0);
    CHECK(strcmp("gla", langcode_three_old("gd")) == 0);
    CHECK(strcmp("gle", langcode_three_old("ga")) == 0);
    CHECK(strcmp("glg", langcode_three_old("gl")) == 0);
    CHECK(strcmp("glv", langcode_three_old("gv")) == 0);
    CHECK(strcmp("gre", langcode_three_old("el")) == 0);
    CHECK(strcmp("grn", langcode_three_old("gn")) == 0);
    CHECK(strcmp("guj", langcode_three_old("gu")) == 0);
    CHECK(strcmp("hat", langcode_three_old("ht")) == 0);
    CHECK(strcmp("hau", langcode_three_old("ha")) == 0);
    CHECK(strcmp("heb", langcode_three_old("he")) == 0);
    CHECK(strcmp("her", langcode_three_old("hz")) == 0);
    CHECK(strcmp("hin", langcode_three_old("hi")) == 0);
    CHECK(strcmp("hmo", langcode_three_old("ho")) == 0);
    CHECK(strcmp("hrv", langcode_three_old("hr")) == 0);
    CHECK(strcmp("hun", langcode_three_old("hu")) == 0);
    CHECK(strcmp("ibo", langcode_three_old("ig")) == 0);
    CHECK(strcmp("ice", langcode_three_old("is")) == 0);
    CHECK(strcmp("ido", langcode_three_old("io")) == 0);
    CHECK(strcmp("iii", langcode_three_old("ii")) == 0);
    CHECK(strcmp("iku", langcode_three_old("iu")) == 0);
    CHECK(strcmp("ile", langcode_three_old("ie")) == 0);
    CHECK(strcmp("ina", langcode_three_old("ia")) == 0);
    CHECK(strcmp("ind", langcode_three_old("id")) == 0);
    CHECK(strcmp("ipk", langcode_three_old("ik")) == 0);
    CHECK(strcmp("ita", langcode_three_old("it")) == 0);
    CHECK(strcmp("jav", langcode_three_old("jv")) == 0);
    CHECK(strcmp("jpn", langcode_three_old("ja")) == 0);
    CHECK(strcmp("kal", langcode_three_old("kl")) == 0);
    CHECK(strcmp("kan", langcode_three_old("kn")) == 0);
    CHECK(strcmp("kas", langcode_three_old("ks")) == 0);
    CHECK(strcmp("kau", langcode_three_old("kr")) == 0);
    CHECK(strcmp("kaz", langcode_three_old("kk")) == 0);
    CHECK(strcmp("khm", langcode_three_old("km")) == 0);
    CHECK(strcmp("kik", langcode_three_old("ki")) == 0);
    CHECK(strcmp("kin", langcode_three_old("rw")) == 0);
    CHECK(strcmp("kir", langcode_three_old("ky")) == 0);
    CHECK(strcmp("kom", langcode_three_old("kv")) == 0);
    CHECK(strcmp("kon", langcode_three_old("kg")) == 0);
    CHECK(strcmp("kor", langcode_three_old("ko")) == 0);
    CHECK(strcmp("kua", langcode_three_old("kj")) == 0);
    CHECK(strcmp("kur", langcode_three_old("ku")) == 0);
    CHECK(strcmp("lao", langcode_three_old("lo")) == 0);
    CHECK(strcmp("lat", langcode_three_old("la")) == 0);
    CHECK(strcmp("lav", langcode_three_old("lv")) == 0);
    CHECK(strcmp("lim", langcode_three_old("li")) == 0);
    CHECK(strcmp("lin", langcode_three_old("ln")) == 0);
    CHECK(strcmp("lit", langcode_three_old("lt")) == 0);
    CHECK(strcmp("ltz", langcode_three_old("lb")) == 0);
    CHECK(strcmp("lub", langcode_three_old("lu")) == 0);
    CHECK(strcmp("lug", langcode_three_old("lg")) == 0);
    CHECK(strcmp("mac", langcode_three_old("mk")) == 0);
    CHECK(strcmp("mah", langcode_three_old("mh")) == 0);
    CHECK(strcmp("mal", langcode_three_old("ml")) == 0);
    CHECK(strcmp("mao", langcode_three_old("mi")) == 0);
    CHECK(strcmp("mar", langcode_three_old("mr")) == 0);
    CHECK(strcmp("may", langcode_three_old("ms")) == 0);
    CHECK(strcmp("mlg", langcode_three_old("mg")) == 0);
    CHECK(strcmp("mlt", langcode_three_old("mt")) == 0);
    CHECK(strcmp("mon", langcode_three_old("mn")) == 0);
    CHECK(strcmp("nau", langcode_three_old("na")) == 0);
    CHECK(strcmp("nav", langcode_three_old("nv")) == 0);
    CHECK(strcmp("nbl", langcode_three_old("nr")) == 0);
    CHECK(strcmp("nde", langcode_three_old("nd")) == 0);
    CHECK(strcmp("ndo", langcode_three_old("ng")) == 0);
    CHECK(strcmp("nep", langcode_three_old("ne")) == 0);
    CHECK(strcmp("nno", langcode_three_old("nn")) == 0);
    CHECK(strcmp("nob", langcode_three_old("nb")) == 0);
    CHECK(strcmp("nor", langcode_three_old("no")) == 0);
    CHECK(strcmp("nya", langcode_three_old("ny")) == 0);
    CHECK(strcmp("oci", langcode_three_old("oc")) == 0);
    CHECK(strcmp("oji", langcode_three_old("oj")) == 0);
    CHECK(strcmp("ori", langcode_three_old("or")) == 0);
    CHECK(strcmp("orm", langcode_three_old("om")) == 0);
    CHECK(strcmp("oss", langcode_three_old("os")) == 0);
    CHECK(strcmp("pan", langcode_three_old("pa")) == 0);
    CHECK(strcmp("per", langcode_three_old("fa")) == 0);
    CHECK(strcmp("pli", langcode_three_old("pi")) == 0);
    CHECK(strcmp("pol", langcode_three_old("pl")) == 0);
    CHECK(strcmp("por", langcode_three_old("pt")) == 0);
    CHECK(strcmp("pus", langcode_three_old("ps")) == 0);
    CHECK(strcmp("que", langcode_three_old("qu")) == 0);
    CHECK(strcmp("roh", langcode_three_old("rm")) == 0);
    CHECK(strcmp("rum", langcode_three_old("ro")) == 0);
    CHECK(strcmp("run", langcode_three_old("rn")) == 0);
    CHECK(strcmp("rus", langcode_three_old("ru")) == 0);
    CHECK(strcmp("sag", langcode_three_old("sg")) == 0);
    CHECK(strcmp("san", langcode_three_old("sa")) == 0);
    CHECK(strcmp("sin", langcode_three_old("si")) == 0);
    CHECK(strcmp("slo", langcode_three_old("sk")) == 0);
    CHECK(strcmp("slv", langcode_three_old("sl")) == 0);
    CHECK(strcmp("sme", langcode_three_old("se")) == 0);
    CHECK(strcmp("smo", langcode_three_old("sm")) == 0);
    CHECK(strcmp("sna", langcode_three_old("sn")) == 0);
    CHECK(strcmp("snd", langcode_three_old("sd")) == 0);
    CHECK(strcmp("som", langcode_three_old("so")) == 0);
    CHECK(strcmp("sot", langcode_three_old("st")) == 0);
    CHECK(strcmp("spa", langcode_three_old("es")) == 0);
    CHECK(strcmp("srd", langcode_three_old("sc")) == 0);
    CHECK(strcmp("srp", langcode_three_old("sr")) == 0);
    CHECK(strcmp("ssw", langcode_three_old("ss")) == 0);
    CHECK(strcmp("sun", langcode_three_old("su")) == 0);
    CHECK(strcmp("swa", langcode_three_old("sw")) == 0);
    CHECK(strcmp("swe", langcode_three_old("sv")) == 0);
    CHECK(strcmp("tah", langcode_three_old("ty")) == 0);
    CHECK(strcmp("tam", langcode_three_old("ta")) == 0);
    CHECK(strcmp("tat", langcode_three_old("tt")) == 0);
    CHECK(strcmp("tel", langcode_three_old("te")) == 0);
    CHECK(strcmp("tgk", langcode_three_old("tg")) == 0);
    CHECK(strcmp("tgl", langcode_three_old("tl")) == 0);
    CHECK(strcmp("tha", langcode_three_old("th")) == 0);
    CHECK(strcmp("tib", langcode_three_old("bo")) == 0);
    CHECK(strcmp("tir", langcode_three_old("ti")) == 0);
    CHECK(strcmp("ton", langcode_three_old("to")) == 0);
    CHECK(strcmp("tsn", langcode_three_old("tn")) == 0);
    CHECK(strcmp("tso", langcode_three_old("ts")) == 0);
    CHECK(strcmp("tuk", langcode_three_old("tk")) == 0);
    CHECK(strcmp("tur", langcode_three_old("tr")) == 0);
    CHECK(strcmp("twi", langcode_three_old("tw")) == 0);
    CHECK(strcmp("uig", langcode_three_old("ug")) == 0);
    CHECK(strcmp("ukr", langcode_three_old("uk")) == 0);
    CHECK(strcmp("urd", langcode_three_old("ur")) == 0);
    CHECK(strcmp("uzb", langcode_three_old("uz")) == 0);
    CHECK(strcmp("ven", langcode_three_old("ve")) == 0);
    CHECK(strcmp("vie", langcode_three_old("vi")) == 0);
    CHECK(strcmp("vol", langcode_three_old("vo")) == 0);
    CHECK(strcmp("wel", langcode_three_old("cy")) == 0);
    CHECK(strcmp("wln", langcode_three_old("wa")) == 0);
    CHECK(strcmp("wol", langcode_three_old("wo")) == 0);
    CHECK(strcmp("xho", langcode_three_old("xh")) == 0);
    CHECK(strcmp("yid", langcode_three_old("yi")) == 0);
    CHECK(strcmp("yor", langcode_three_old("yo")) == 0);
    CHECK(strcmp("zha", langcode_three_old("za")) == 0);
    CHECK(strcmp("zul", langcode_three_old("zu")) == 0);
}

static void test_lang_code_str_old() {
    CHECK(string{"aar"} == langcode_three_old(string{"aa"}));
    CHECK(string{"abk"} == langcode_three_old(string{"ab"}));
    CHECK(string{"afr"} == langcode_three_old(string{"af"}));
    CHECK(string{"aka"} == langcode_three_old(string{"ak"}));
    CHECK(string{"alb"} == langcode_three_old(string{"sq"}));
    CHECK(string{"amh"} == langcode_three_old(string{"am"}));
    CHECK(string{"ara"} == langcode_three_old(string{"ar"}));
    CHECK(string{"arg"} == langcode_three_old(string{"an"}));
    CHECK(string{"arm"} == langcode_three_old(string{"hy"}));
    CHECK(string{"asm"} == langcode_three_old(string{"as"}));
    CHECK(string{"ava"} == langcode_three_old(string{"av"}));
    CHECK(string{"ave"} == langcode_three_old(string{"ae"}));
    CHECK(string{"aym"} == langcode_three_old(string{"ay"}));
    CHECK(string{"aze"} == langcode_three_old(string{"az"}));
    CHECK(string{"bak"} == langcode_three_old(string{"ba"}));
    CHECK(string{"bam"} == langcode_three_old(string{"bm"}));
    CHECK(string{"baq"} == langcode_three_old(string{"eu"}));
    CHECK(string{"bel"} == langcode_three_old(string{"be"}));
    CHECK(string{"ben"} == langcode_three_old(string{"bn"}));
    CHECK(string{"bih"} == langcode_three_old(string{"bh"}));
    CHECK(string{"bis"} == langcode_three_old(string{"bi"}));
    CHECK(string{"bos"} == langcode_three_old(string{"bs"}));
    CHECK(string{"bre"} == langcode_three_old(string{"br"}));
    CHECK(string{"bul"} == langcode_three_old(string{"bg"}));
    CHECK(string{"bur"} == langcode_three_old(string{"my"}));
    CHECK(string{"cat"} == langcode_three_old(string{"ca"}));
    CHECK(string{"cha"} == langcode_three_old(string{"ch"}));
    CHECK(string{"che"} == langcode_three_old(string{"ce"}));
    CHECK(string{"chi"} == langcode_three_old(string{"zh"}));
    CHECK(string{"chu"} == langcode_three_old(string{"cu"}));
    CHECK(string{"chv"} == langcode_three_old(string{"cv"}));
    CHECK(string{"cor"} == langcode_three_old(string{"kw"}));
    CHECK(string{"cos"} == langcode_three_old(string{"co"}));
    CHECK(string{"cre"} == langcode_three_old(string{"cr"}));
    CHECK(string{"cze"} == langcode_three_old(string{"cs"}));
    CHECK(string{"dan"} == langcode_three_old(string{"da"}));
    CHECK(string{"div"} == langcode_three_old(string{"dv"}));
    CHECK(string{"dut"} == langcode_three_old(string{"nl"}));
    CHECK(string{"dzo"} == langcode_three_old(string{"dz"}));
    CHECK(string{"eng"} == langcode_three_old(string{"en"}));
    CHECK(string{"epo"} == langcode_three_old(string{"eo"}));
    CHECK(string{"est"} == langcode_three_old(string{"et"}));
    CHECK(string{"ewe"} == langcode_three_old(string{"ee"}));
    CHECK(string{"fao"} == langcode_three_old(string{"fo"}));
    CHECK(string{"fij"} == langcode_three_old(string{"fj"}));
    CHECK(string{"fin"} == langcode_three_old(string{"fi"}));
    CHECK(string{"fre"} == langcode_three_old(string{"fr"}));
    CHECK(string{"fry"} == langcode_three_old(string{"fy"}));
    CHECK(string{"ful"} == langcode_three_old(string{"ff"}));
    CHECK(string{"geo"} == langcode_three_old(string{"ka"}));
    CHECK(string{"ger"} == langcode_three_old(string{"de"}));
    CHECK(string{"gla"} == langcode_three_old(string{"gd"}));
    CHECK(string{"gle"} == langcode_three_old(string{"ga"}));
    CHECK(string{"glg"} == langcode_three_old(string{"gl"}));
    CHECK(string{"glv"} == langcode_three_old(string{"gv"}));
    CHECK(string{"gre"} == langcode_three_old(string{"el"}));
    CHECK(string{"grn"} == langcode_three_old(string{"gn"}));
    CHECK(string{"guj"} == langcode_three_old(string{"gu"}));
    CHECK(string{"hat"} == langcode_three_old(string{"ht"}));
    CHECK(string{"hau"} == langcode_three_old(string{"ha"}));
    CHECK(string{"heb"} == langcode_three_old(string{"he"}));
    CHECK(string{"her"} == langcode_three_old(string{"hz"}));
    CHECK(string{"hin"} == langcode_three_old(string{"hi"}));
    CHECK(string{"hmo"} == langcode_three_old(string{"ho"}));
    CHECK(string{"hrv"} == langcode_three_old(string{"hr"}));
    CHECK(string{"hun"} == langcode_three_old(string{"hu"}));
    CHECK(string{"ibo"} == langcode_three_old(string{"ig"}));
    CHECK(string{"ice"} == langcode_three_old(string{"is"}));
    CHECK(string{"ido"} == langcode_three_old(string{"io"}));
    CHECK(string{"iii"} == langcode_three_old(string{"ii"}));
    CHECK(string{"iku"} == langcode_three_old(string{"iu"}));
    CHECK(string{"ile"} == langcode_three_old(string{"ie"}));
    CHECK(string{"ina"} == langcode_three_old(string{"ia"}));
    CHECK(string{"ind"} == langcode_three_old(string{"id"}));
    CHECK(string{"ipk"} == langcode_three_old(string{"ik"}));
    CHECK(string{"ita"} == langcode_three_old(string{"it"}));
    CHECK(string{"jav"} == langcode_three_old(string{"jv"}));
    CHECK(string{"jpn"} == langcode_three_old(string{"ja"}));
    CHECK(string{"kal"} == langcode_three_old(string{"kl"}));
    CHECK(string{"kan"} == langcode_three_old(string{"kn"}));
    CHECK(string{"kas"} == langcode_three_old(string{"ks"}));
    CHECK(string{"kau"} == langcode_three_old(string{"kr"}));
    CHECK(string{"kaz"} == langcode_three_old(string{"kk"}));
    CHECK(string{"khm"} == langcode_three_old(string{"km"}));
    CHECK(string{"kik"} == langcode_three_old(string{"ki"}));
    CHECK(string{"kin"} == langcode_three_old(string{"rw"}));
    CHECK(string{"kir"} == langcode_three_old(string{"ky"}));
    CHECK(string{"kom"} == langcode_three_old(string{"kv"}));
    CHECK(string{"kon"} == langcode_three_old(string{"kg"}));
    CHECK(string{"kor"} == langcode_three_old(string{"ko"}));
    CHECK(string{"kua"} == langcode_three_old(string{"kj"}));
    CHECK(string{"kur"} == langcode_three_old(string{"ku"}));
    CHECK(string{"lao"} == langcode_three_old(string{"lo"}));
    CHECK(string{"lat"} == langcode_three_old(string{"la"}));
    CHECK(string{"lav"} == langcode_three_old(string{"lv"}));
    CHECK(string{"lim"} == langcode_three_old(string{"li"}));
    CHECK(string{"lin"} == langcode_three_old(string{"ln"}));
    CHECK(string{"lit"} == langcode_three_old(string{"lt"}));
    CHECK(string{"ltz"} == langcode_three_old(string{"lb"}));
    CHECK(string{"lub"} == langcode_three_old(string{"lu"}));
    CHECK(string{"lug"} == langcode_three_old(string{"lg"}));
    CHECK(string{"mac"} == langcode_three_old(string{"mk"}));
    CHECK(string{"mah"} == langcode_three_old(string{"mh"}));
    CHECK(string{"mal"} == langcode_three_old(string{"ml"}));
    CHECK(string{"mao"} == langcode_three_old(string{"mi"}));
    CHECK(string{"mar"} == langcode_three_old(string{"mr"}));
    CHECK(string{"may"} == langcode_three_old(string{"ms"}));
    CHECK(string{"mlg"} == langcode_three_old(string{"mg"}));
    CHECK(string{"mlt"} == langcode_three_old(string{"mt"}));
    CHECK(string{"mon"} == langcode_three_old(string{"mn"}));
    CHECK(string{"nau"} == langcode_three_old(string{"na"}));
    CHECK(string{"nav"} == langcode_three_old(string{"nv"}));
    CHECK(string{"nbl"} == langcode_three_old(string{"nr"}));
    CHECK(string{"nde"} == langcode_three_old(string{"nd"}));
    CHECK(string{"ndo"} == langcode_three_old(string{"ng"}));
    CHECK(string{"nep"} == langcode_three_old(string{"ne"}));
    CHECK(string{"nno"} == langcode_three_old(string{"nn"}));
    CHECK(string{"nob"} == langcode_three_old(string{"nb"}));
    CHECK(string{"nor"} == langcode_three_old(string{"no"}));
    CHECK(string{"nya"} == langcode_three_old(string{"ny"}));
    CHECK(string{"oci"} == langcode_three_old(string{"oc"}));
    CHECK(string{"oji"} == langcode_three_old(string{"oj"}));
    CHECK(string{"ori"} == langcode_three_old(string{"or"}));
    CHECK(string{"orm"} == langcode_three_old(string{"om"}));
    CHECK(string{"oss"} == langcode_three_old(string{"os"}));
    CHECK(string{"pan"} == langcode_three_old(string{"pa"}));
    CHECK(string{"per"} == langcode_three_old(string{"fa"}));
    CHECK(string{"pli"} == langcode_three_old(string{"pi"}));
    CHECK(string{"pol"} == langcode_three_old(string{"pl"}));
    CHECK(string{"por"} == langcode_three_old(string{"pt"}));
    CHECK(string{"pus"} == langcode_three_old(string{"ps"}));
    CHECK(string{"que"} == langcode_three_old(string{"qu"}));
    CHECK(string{"roh"} == langcode_three_old(string{"rm"}));
    CHECK(string{"rum"} == langcode_three_old(string{"ro"}));
    CHECK(string{"run"} == langcode_three_old(string{"rn"}));
    CHECK(string{"rus"} == langcode_three_old(string{"ru"}));
    CHECK(string{"sag"} == langcode_three_old(string{"sg"}));
    CHECK(string{"san"} == langcode_three_old(string{"sa"}));
    CHECK(string{"sin"} == langcode_three_old(string{"si"}));
    CHECK(string{"slo"} == langcode_three_old(string{"sk"}));
    CHECK(string{"slv"} == langcode_three_old(string{"sl"}));
    CHECK(string{"sme"} == langcode_three_old(string{"se"}));
    CHECK(string{"smo"} == langcode_three_old(string{"sm"}));
    CHECK(string{"sna"} == langcode_three_old(string{"sn"}));
    CHECK(string{"snd"} == langcode_three_old(string{"sd"}));
    CHECK(string{"som"} == langcode_three_old(string{"so"}));
    CHECK(string{"sot"} == langcode_three_old(string{"st"}));
    CHECK(string{"spa"} == langcode_three_old(string{"es"}));
    CHECK(string{"srd"} == langcode_three_old(string{"sc"}));
    CHECK(string{"srp"} == langcode_three_old(string{"sr"}));
    CHECK(string{"ssw"} == langcode_three_old(string{"ss"}));
    CHECK(string{"sun"} == langcode_three_old(string{"su"}));
    CHECK(string{"swa"} == langcode_three_old(string{"sw"}));
    CHECK(string{"swe"} == langcode_three_old(string{"sv"}));
    CHECK(string{"tah"} == langcode_three_old(string{"ty"}));
    CHECK(string{"tam"} == langcode_three_old(string{"ta"}));
    CHECK(string{"tat"} == langcode_three_old(string{"tt"}));
    CHECK(string{"tel"} == langcode_three_old(string{"te"}));
    CHECK(string{"tgk"} == langcode_three_old(string{"tg"}));
    CHECK(string{"tgl"} == langcode_three_old(string{"tl"}));
    CHECK(string{"tha"} == langcode_three_old(string{"th"}));
    CHECK(string{"tib"} == langcode_three_old(string{"bo"}));
    CHECK(string{"tir"} == langcode_three_old(string{"ti"}));
    CHECK(string{"ton"} == langcode_three_old(string{"to"}));
    CHECK(string{"tsn"} == langcode_three_old(string{"tn"}));
    CHECK(string{"tso"} == langcode_three_old(string{"ts"}));
    CHECK(string{"tuk"} == langcode_three_old(string{"tk"}));
    CHECK(string{"tur"} == langcode_three_old(string{"tr"}));
    CHECK(string{"twi"} == langcode_three_old(string{"tw"}));
    CHECK(string{"uig"} == langcode_three_old(string{"ug"}));
    CHECK(string{"ukr"} == langcode_three_old(string{"uk"}));
    CHECK(string{"urd"} == langcode_three_old(string{"ur"}));
    CHECK(string{"uzb"} == langcode_three_old(string{"uz"}));
    CHECK(string{"ven"} == langcode_three_old(string{"ve"}));
    CHECK(string{"vie"} == langcode_three_old(string{"vi"}));
    CHECK(string{"vol"} == langcode_three_old(string{"vo"}));
    CHECK(string{"wel"} == langcode_three_old(string{"cy"}));
    CHECK(string{"wln"} == langcode_three_old(string{"wa"}));
    CHECK(string{"wol"} == langcode_three_old(string{"wo"}));
    CHECK(string{"xho"} == langcode_three_old(string{"xh"}));
    CHECK(string{"yid"} == langcode_three_old(string{"yi"}));
    CHECK(string{"yor"} == langcode_three_old(string{"yo"}));
    CHECK(string{"zha"} == langcode_three_old(string{"za"}));
    CHECK(string{"zul"} == langcode_three_old(string{"zu"}));
}

static void test_lang_code_not_found_old() {
    CHECK(strcmp("bb", langcode_three_old("bb")) == 0);
    CHECK(strcmp("cc", langcode_three_old("cc")) == 0);
    CHECK(strcmp("dd", langcode_three_old("dd")) == 0);
    CHECK(strcmp("gg", langcode_three_old("gg")) == 0);
    CHECK(strcmp("hh", langcode_three_old("hh")) == 0);
    CHECK(strcmp("jj", langcode_three_old("jj")) == 0);
    CHECK(strcmp("ll", langcode_three_old("ll")) == 0);
    CHECK(strcmp("mm", langcode_three_old("mm")) == 0);
    CHECK(strcmp("oo", langcode_three_old("oo")) == 0);
    CHECK(strcmp("pp", langcode_three_old("pp")) == 0);
    CHECK(strcmp("qq", langcode_three_old("qq")) == 0);
    CHECK(strcmp("rr", langcode_three_old("rr")) == 0);
    CHECK(strcmp("uu", langcode_three_old("uu")) == 0);
    CHECK(strcmp("vv", langcode_three_old("vv")) == 0);
    CHECK(strcmp("ww", langcode_three_old("ww")) == 0);
    CHECK(strcmp("xx", langcode_three_old("xx")) == 0);
    CHECK(strcmp("yy", langcode_three_old("yy")) == 0);
    CHECK(strcmp("zz", langcode_three_old("zz")) == 0);
}

static void test_lang_code_str_not_found_old() {
    CHECK(langcode_three_old(string{"bb"}) == string{"bb"});
    CHECK(langcode_three_old(string{"cc"}) == string{"cc"});
    CHECK(langcode_three_old(string{"dd"}) == string{"dd"});
    CHECK(langcode_three_old(string{"gg"}) == string{"gg"});
    CHECK(langcode_three_old(string{"hh"}) == string{"hh"});
    CHECK(langcode_three_old(string{"jj"}) == string{"jj"});
    CHECK(langcode_three_old(string{"ll"}) == string{"ll"});
    CHECK(langcode_three_old(string{"mm"}) == string{"mm"});
    CHECK(langcode_three_old(string{"oo"}) == string{"oo"});
    CHECK(langcode_three_old(string{"pp"}) == string{"pp"});
    CHECK(langcode_three_old(string{"qq"}) == string{"qq"});
    CHECK(langcode_three_old(string{"rr"}) == string{"rr"});
    CHECK(langcode_three_old(string{"uu"}) == string{"uu"});
    CHECK(langcode_three_old(string{"vv"}) == string{"vv"});
    CHECK(langcode_three_old(string{"ww"}) == string{"ww"});
    CHECK(langcode_three_old(string{"xx"}) == string{"xx"});
    CHECK(langcode_three_old(string{"yy"}) == string{"yy"});
    CHECK(langcode_three_old(string{"zz"}) == string{"zz"});
}

static void test_lang_code_new() {
    CHECK(strcmp("aar", langcode_three_new("aa")) == 0);
    CHECK(strcmp("abk", langcode_three_new("ab")) == 0);
    CHECK(strcmp("afr", langcode_three_new("af")) == 0);
    CHECK(strcmp("aka", langcode_three_new("ak")) == 0);
    CHECK(strcmp("alb", langcode_three_new("sq")) == 0);
    CHECK(strcmp("amh", langcode_three_new("am")) == 0);
    CHECK(strcmp("ara", langcode_three_new("ar")) == 0);
    CHECK(strcmp("arg", langcode_three_new("an")) == 0);
    CHECK(strcmp("arm", langcode_three_new("hy")) == 0);
    CHECK(strcmp("asm", langcode_three_new("as")) == 0);
    CHECK(strcmp("ava", langcode_three_new("av")) == 0);
    CHECK(strcmp("ave", langcode_three_new("ae")) == 0);
    CHECK(strcmp("aym", langcode_three_new("ay")) == 0);
    CHECK(strcmp("aze", langcode_three_new("az")) == 0);
    CHECK(strcmp("bak", langcode_three_new("ba")) == 0);
    CHECK(strcmp("bam", langcode_three_new("bm")) == 0);
    CHECK(strcmp("baq", langcode_three_new("eu")) == 0);
    CHECK(strcmp("bel", langcode_three_new("be")) == 0);
    CHECK(strcmp("ben", langcode_three_new("bn")) == 0);
    CHECK(strcmp("bih", langcode_three_new("bh")) == 0);
    CHECK(strcmp("bis", langcode_three_new("bi")) == 0);
    CHECK(strcmp("bos", langcode_three_new("bs")) == 0);
    CHECK(strcmp("bre", langcode_three_new("br")) == 0);
    CHECK(strcmp("bul", langcode_three_new("bg")) == 0);
    CHECK(strcmp("bur", langcode_three_new("my")) == 0);
    CHECK(strcmp("cat", langcode_three_new("ca")) == 0);
    CHECK(strcmp("cha", langcode_three_new("ch")) == 0);
    CHECK(strcmp("che", langcode_three_new("ce")) == 0);
    CHECK(strcmp("chi", langcode_three_new("zh")) == 0);
    CHECK(strcmp("chu", langcode_three_new("cu")) == 0);
    CHECK(strcmp("chv", langcode_three_new("cv")) == 0);
    CHECK(strcmp("cor", langcode_three_new("kw")) == 0);
    CHECK(strcmp("cos", langcode_three_new("co")) == 0);
    CHECK(strcmp("cre", langcode_three_new("cr")) == 0);
    CHECK(strcmp("cze", langcode_three_new("cs")) == 0);
    CHECK(strcmp("dan", langcode_three_new("da")) == 0);
    CHECK(strcmp("div", langcode_three_new("dv")) == 0);
    CHECK(strcmp("dut", langcode_three_new("nl")) == 0);
    CHECK(strcmp("dzo", langcode_three_new("dz")) == 0);
    CHECK(strcmp("eng", langcode_three_new("en")) == 0);
    CHECK(strcmp("epo", langcode_three_new("eo")) == 0);
    CHECK(strcmp("est", langcode_three_new("et")) == 0);
    CHECK(strcmp("ewe", langcode_three_new("ee")) == 0);
    CHECK(strcmp("fao", langcode_three_new("fo")) == 0);
    CHECK(strcmp("fij", langcode_three_new("fj")) == 0);
    CHECK(strcmp("fin", langcode_three_new("fi")) == 0);
    CHECK(strcmp("fre", langcode_three_new("fr")) == 0);
    CHECK(strcmp("fry", langcode_three_new("fy")) == 0);
    CHECK(strcmp("ful", langcode_three_new("ff")) == 0);
    CHECK(strcmp("geo", langcode_three_new("ka")) == 0);
    CHECK(strcmp("ger", langcode_three_new("de")) == 0);
    CHECK(strcmp("gla", langcode_three_new("gd")) == 0);
    CHECK(strcmp("gle", langcode_three_new("ga")) == 0);
    CHECK(strcmp("glg", langcode_three_new("gl")) == 0);
    CHECK(strcmp("glv", langcode_three_new("gv")) == 0);
    CHECK(strcmp("gre", langcode_three_new("el")) == 0);
    CHECK(strcmp("grn", langcode_three_new("gn")) == 0);
    CHECK(strcmp("guj", langcode_three_new("gu")) == 0);
    CHECK(strcmp("hat", langcode_three_new("ht")) == 0);
    CHECK(strcmp("hau", langcode_three_new("ha")) == 0);
    CHECK(strcmp("heb", langcode_three_new("he")) == 0);
    CHECK(strcmp("her", langcode_three_new("hz")) == 0);
    CHECK(strcmp("hin", langcode_three_new("hi")) == 0);
    CHECK(strcmp("hmo", langcode_three_new("ho")) == 0);
    CHECK(strcmp("hrv", langcode_three_new("hr")) == 0);
    CHECK(strcmp("hun", langcode_three_new("hu")) == 0);
    CHECK(strcmp("ibo", langcode_three_new("ig")) == 0);
    CHECK(strcmp("ice", langcode_three_new("is")) == 0);
    CHECK(strcmp("ido", langcode_three_new("io")) == 0);
    CHECK(strcmp("iii", langcode_three_new("ii")) == 0);
    CHECK(strcmp("iku", langcode_three_new("iu")) == 0);
    CHECK(strcmp("ile", langcode_three_new("ie")) == 0);
    CHECK(strcmp("ina", langcode_three_new("ia")) == 0);
    CHECK(strcmp("ind", langcode_three_new("id")) == 0);
    CHECK(strcmp("ipk", langcode_three_new("ik")) == 0);
    CHECK(strcmp("ita", langcode_three_new("it")) == 0);
    CHECK(strcmp("jav", langcode_three_new("jv")) == 0);
    CHECK(strcmp("jpn", langcode_three_new("ja")) == 0);
    CHECK(strcmp("kal", langcode_three_new("kl")) == 0);
    CHECK(strcmp("kan", langcode_three_new("kn")) == 0);
    CHECK(strcmp("kas", langcode_three_new("ks")) == 0);
    CHECK(strcmp("kau", langcode_three_new("kr")) == 0);
    CHECK(strcmp("kaz", langcode_three_new("kk")) == 0);
    CHECK(strcmp("khm", langcode_three_new("km")) == 0);
    CHECK(strcmp("kik", langcode_three_new("ki")) == 0);
    CHECK(strcmp("kin", langcode_three_new("rw")) == 0);
    CHECK(strcmp("kir", langcode_three_new("ky")) == 0);
    CHECK(strcmp("kom", langcode_three_new("kv")) == 0);
    CHECK(strcmp("kon", langcode_three_new("kg")) == 0);
    CHECK(strcmp("kor", langcode_three_new("ko")) == 0);
    CHECK(strcmp("kua", langcode_three_new("kj")) == 0);
    CHECK(strcmp("kur", langcode_three_new("ku")) == 0);
    CHECK(strcmp("lao", langcode_three_new("lo")) == 0);
    CHECK(strcmp("lat", langcode_three_new("la")) == 0);
    CHECK(strcmp("lav", langcode_three_new("lv")) == 0);
    CHECK(strcmp("lim", langcode_three_new("li")) == 0);
    CHECK(strcmp("lin", langcode_three_new("ln")) == 0);
    CHECK(strcmp("lit", langcode_three_new("lt")) == 0);
    CHECK(strcmp("ltz", langcode_three_new("lb")) == 0);
    CHECK(strcmp("lub", langcode_three_new("lu")) == 0);
    CHECK(strcmp("lug", langcode_three_new("lg")) == 0);
    CHECK(strcmp("mac", langcode_three_new("mk")) == 0);
    CHECK(strcmp("mah", langcode_three_new("mh")) == 0);
    CHECK(strcmp("mal", langcode_three_new("ml")) == 0);
    CHECK(strcmp("mao", langcode_three_new("mi")) == 0);
    CHECK(strcmp("mar", langcode_three_new("mr")) == 0);
    CHECK(strcmp("may", langcode_three_new("ms")) == 0);
    CHECK(strcmp("mlg", langcode_three_new("mg")) == 0);
    CHECK(strcmp("mlt", langcode_three_new("mt")) == 0);
    CHECK(strcmp("mon", langcode_three_new("mn")) == 0);
    CHECK(strcmp("nau", langcode_three_new("na")) == 0);
    CHECK(strcmp("nav", langcode_three_new("nv")) == 0);
    CHECK(strcmp("nbl", langcode_three_new("nr")) == 0);
    CHECK(strcmp("nde", langcode_three_new("nd")) == 0);
    CHECK(strcmp("ndo", langcode_three_new("ng")) == 0);
    CHECK(strcmp("nep", langcode_three_new("ne")) == 0);
    CHECK(strcmp("nno", langcode_three_new("nn")) == 0);
    CHECK(strcmp("nob", langcode_three_new("nb")) == 0);
    CHECK(strcmp("nor", langcode_three_new("no")) == 0);
    CHECK(strcmp("nya", langcode_three_new("ny")) == 0);
    CHECK(strcmp("oci", langcode_three_new("oc")) == 0);
    CHECK(strcmp("oji", langcode_three_new("oj")) == 0);
    CHECK(strcmp("ori", langcode_three_new("or")) == 0);
    CHECK(strcmp("orm", langcode_three_new("om")) == 0);
    CHECK(strcmp("oss", langcode_three_new("os")) == 0);
    CHECK(strcmp("pan", langcode_three_new("pa")) == 0);
    CHECK(strcmp("per", langcode_three_new("fa")) == 0);
    CHECK(strcmp("pli", langcode_three_new("pi")) == 0);
    CHECK(strcmp("pol", langcode_three_new("pl")) == 0);
    CHECK(strcmp("por", langcode_three_new("pt")) == 0);
    CHECK(strcmp("pus", langcode_three_new("ps")) == 0);
    CHECK(strcmp("que", langcode_three_new("qu")) == 0);
    CHECK(strcmp("roh", langcode_three_new("rm")) == 0);
    CHECK(strcmp("rum", langcode_three_new("ro")) == 0);
    CHECK(strcmp("run", langcode_three_new("rn")) == 0);
    CHECK(strcmp("rus", langcode_three_new("ru")) == 0);
    CHECK(strcmp("sag", langcode_three_new("sg")) == 0);
    CHECK(strcmp("san", langcode_three_new("sa")) == 0);
    CHECK(strcmp("sin", langcode_three_new("si")) == 0);
    CHECK(strcmp("slo", langcode_three_new("sk")) == 0);
    CHECK(strcmp("slv", langcode_three_new("sl")) == 0);
    CHECK(strcmp("sme", langcode_three_new("se")) == 0);
    CHECK(strcmp("smo", langcode_three_new("sm")) == 0);
    CHECK(strcmp("sna", langcode_three_new("sn")) == 0);
    CHECK(strcmp("snd", langcode_three_new("sd")) == 0);
    CHECK(strcmp("som", langcode_three_new("so")) == 0);
    CHECK(strcmp("sot", langcode_three_new("st")) == 0);
    CHECK(strcmp("spa", langcode_three_new("es")) == 0);
    CHECK(strcmp("srd", langcode_three_new("sc")) == 0);
    CHECK(strcmp("srp", langcode_three_new("sr")) == 0);
    CHECK(strcmp("ssw", langcode_three_new("ss")) == 0);
    CHECK(strcmp("sun", langcode_three_new("su")) == 0);
    CHECK(strcmp("swa", langcode_three_new("sw")) == 0);
    CHECK(strcmp("swe", langcode_three_new("sv")) == 0);
    CHECK(strcmp("tah", langcode_three_new("ty")) == 0);
    CHECK(strcmp("tam", langcode_three_new("ta")) == 0);
    CHECK(strcmp("tat", langcode_three_new("tt")) == 0);
    CHECK(strcmp("tel", langcode_three_new("te")) == 0);
    CHECK(strcmp("tgk", langcode_three_new("tg")) == 0);
    CHECK(strcmp("tgl", langcode_three_new("tl")) == 0);
    CHECK(strcmp("tha", langcode_three_new("th")) == 0);
    CHECK(strcmp("tib", langcode_three_new("bo")) == 0);
    CHECK(strcmp("tir", langcode_three_new("ti")) == 0);
    CHECK(strcmp("ton", langcode_three_new("to")) == 0);
    CHECK(strcmp("tsn", langcode_three_new("tn")) == 0);
    CHECK(strcmp("tso", langcode_three_new("ts")) == 0);
    CHECK(strcmp("tuk", langcode_three_new("tk")) == 0);
    CHECK(strcmp("tur", langcode_three_new("tr")) == 0);
    CHECK(strcmp("twi", langcode_three_new("tw")) == 0);
    CHECK(strcmp("uig", langcode_three_new("ug")) == 0);
    CHECK(strcmp("ukr", langcode_three_new("uk")) == 0);
    CHECK(strcmp("urd", langcode_three_new("ur")) == 0);
    CHECK(strcmp("uzb", langcode_three_new("uz")) == 0);
    CHECK(strcmp("ven", langcode_three_new("ve")) == 0);
    CHECK(strcmp("vie", langcode_three_new("vi")) == 0);
    CHECK(strcmp("vol", langcode_three_new("vo")) == 0);
    CHECK(strcmp("wel", langcode_three_new("cy")) == 0);
    CHECK(strcmp("wln", langcode_three_new("wa")) == 0);
    CHECK(strcmp("wol", langcode_three_new("wo")) == 0);
    CHECK(strcmp("xho", langcode_three_new("xh")) == 0);
    CHECK(strcmp("yid", langcode_three_new("yi")) == 0);
    CHECK(strcmp("yor", langcode_three_new("yo")) == 0);
    CHECK(strcmp("zha", langcode_three_new("za")) == 0);
    CHECK(strcmp("zul", langcode_three_new("zu")) == 0);
}

static void test_lang_code_str_new() {
    CHECK(string{"aar"} == langcode_three_new(string{"aa"}));
    CHECK(string{"abk"} == langcode_three_new(string{"ab"}));
    CHECK(string{"afr"} == langcode_three_new(string{"af"}));
    CHECK(string{"aka"} == langcode_three_new(string{"ak"}));
    CHECK(string{"alb"} == langcode_three_new(string{"sq"}));
    CHECK(string{"amh"} == langcode_three_new(string{"am"}));
    CHECK(string{"ara"} == langcode_three_new(string{"ar"}));
    CHECK(string{"arg"} == langcode_three_new(string{"an"}));
    CHECK(string{"arm"} == langcode_three_new(string{"hy"}));
    CHECK(string{"asm"} == langcode_three_new(string{"as"}));
    CHECK(string{"ava"} == langcode_three_new(string{"av"}));
    CHECK(string{"ave"} == langcode_three_new(string{"ae"}));
    CHECK(string{"aym"} == langcode_three_new(string{"ay"}));
    CHECK(string{"aze"} == langcode_three_new(string{"az"}));
    CHECK(string{"bak"} == langcode_three_new(string{"ba"}));
    CHECK(string{"bam"} == langcode_three_new(string{"bm"}));
    CHECK(string{"baq"} == langcode_three_new(string{"eu"}));
    CHECK(string{"bel"} == langcode_three_new(string{"be"}));
    CHECK(string{"ben"} == langcode_three_new(string{"bn"}));
    CHECK(string{"bih"} == langcode_three_new(string{"bh"}));
    CHECK(string{"bis"} == langcode_three_new(string{"bi"}));
    CHECK(string{"bos"} == langcode_three_new(string{"bs"}));
    CHECK(string{"bre"} == langcode_three_new(string{"br"}));
    CHECK(string{"bul"} == langcode_three_new(string{"bg"}));
    CHECK(string{"bur"} == langcode_three_new(string{"my"}));
    CHECK(string{"cat"} == langcode_three_new(string{"ca"}));
    CHECK(string{"cha"} == langcode_three_new(string{"ch"}));
    CHECK(string{"che"} == langcode_three_new(string{"ce"}));
    CHECK(string{"chi"} == langcode_three_new(string{"zh"}));
    CHECK(string{"chu"} == langcode_three_new(string{"cu"}));
    CHECK(string{"chv"} == langcode_three_new(string{"cv"}));
    CHECK(string{"cor"} == langcode_three_new(string{"kw"}));
    CHECK(string{"cos"} == langcode_three_new(string{"co"}));
    CHECK(string{"cre"} == langcode_three_new(string{"cr"}));
    CHECK(string{"cze"} == langcode_three_new(string{"cs"}));
    CHECK(string{"dan"} == langcode_three_new(string{"da"}));
    CHECK(string{"div"} == langcode_three_new(string{"dv"}));
    CHECK(string{"dut"} == langcode_three_new(string{"nl"}));
    CHECK(string{"dzo"} == langcode_three_new(string{"dz"}));
    CHECK(string{"eng"} == langcode_three_new(string{"en"}));
    CHECK(string{"epo"} == langcode_three_new(string{"eo"}));
    CHECK(string{"est"} == langcode_three_new(string{"et"}));
    CHECK(string{"ewe"} == langcode_three_new(string{"ee"}));
    CHECK(string{"fao"} == langcode_three_new(string{"fo"}));
    CHECK(string{"fij"} == langcode_three_new(string{"fj"}));
    CHECK(string{"fin"} == langcode_three_new(string{"fi"}));
    CHECK(string{"fre"} == langcode_three_new(string{"fr"}));
    CHECK(string{"fry"} == langcode_three_new(string{"fy"}));
    CHECK(string{"ful"} == langcode_three_new(string{"ff"}));
    CHECK(string{"geo"} == langcode_three_new(string{"ka"}));
    CHECK(string{"ger"} == langcode_three_new(string{"de"}));
    CHECK(string{"gla"} == langcode_three_new(string{"gd"}));
    CHECK(string{"gle"} == langcode_three_new(string{"ga"}));
    CHECK(string{"glg"} == langcode_three_new(string{"gl"}));
    CHECK(string{"glv"} == langcode_three_new(string{"gv"}));
    CHECK(string{"gre"} == langcode_three_new(string{"el"}));
    CHECK(string{"grn"} == langcode_three_new(string{"gn"}));
    CHECK(string{"guj"} == langcode_three_new(string{"gu"}));
    CHECK(string{"hat"} == langcode_three_new(string{"ht"}));
    CHECK(string{"hau"} == langcode_three_new(string{"ha"}));
    CHECK(string{"heb"} == langcode_three_new(string{"he"}));
    CHECK(string{"her"} == langcode_three_new(string{"hz"}));
    CHECK(string{"hin"} == langcode_three_new(string{"hi"}));
    CHECK(string{"hmo"} == langcode_three_new(string{"ho"}));
    CHECK(string{"hrv"} == langcode_three_new(string{"hr"}));
    CHECK(string{"hun"} == langcode_three_new(string{"hu"}));
    CHECK(string{"ibo"} == langcode_three_new(string{"ig"}));
    CHECK(string{"ice"} == langcode_three_new(string{"is"}));
    CHECK(string{"ido"} == langcode_three_new(string{"io"}));
    CHECK(string{"iii"} == langcode_three_new(string{"ii"}));
    CHECK(string{"iku"} == langcode_three_new(string{"iu"}));
    CHECK(string{"ile"} == langcode_three_new(string{"ie"}));
    CHECK(string{"ina"} == langcode_three_new(string{"ia"}));
    CHECK(string{"ind"} == langcode_three_new(string{"id"}));
    CHECK(string{"ipk"} == langcode_three_new(string{"ik"}));
    CHECK(string{"ita"} == langcode_three_new(string{"it"}));
    CHECK(string{"jav"} == langcode_three_new(string{"jv"}));
    CHECK(string{"jpn"} == langcode_three_new(string{"ja"}));
    CHECK(string{"kal"} == langcode_three_new(string{"kl"}));
    CHECK(string{"kan"} == langcode_three_new(string{"kn"}));
    CHECK(string{"kas"} == langcode_three_new(string{"ks"}));
    CHECK(string{"kau"} == langcode_three_new(string{"kr"}));
    CHECK(string{"kaz"} == langcode_three_new(string{"kk"}));
    CHECK(string{"khm"} == langcode_three_new(string{"km"}));
    CHECK(string{"kik"} == langcode_three_new(string{"ki"}));
    CHECK(string{"kin"} == langcode_three_new(string{"rw"}));
    CHECK(string{"kir"} == langcode_three_new(string{"ky"}));
    CHECK(string{"kom"} == langcode_three_new(string{"kv"}));
    CHECK(string{"kon"} == langcode_three_new(string{"kg"}));
    CHECK(string{"kor"} == langcode_three_new(string{"ko"}));
    CHECK(string{"kua"} == langcode_three_new(string{"kj"}));
    CHECK(string{"kur"} == langcode_three_new(string{"ku"}));
    CHECK(string{"lao"} == langcode_three_new(string{"lo"}));
    CHECK(string{"lat"} == langcode_three_new(string{"la"}));
    CHECK(string{"lav"} == langcode_three_new(string{"lv"}));
    CHECK(string{"lim"} == langcode_three_new(string{"li"}));
    CHECK(string{"lin"} == langcode_three_new(string{"ln"}));
    CHECK(string{"lit"} == langcode_three_new(string{"lt"}));
    CHECK(string{"ltz"} == langcode_three_new(string{"lb"}));
    CHECK(string{"lub"} == langcode_three_new(string{"lu"}));
    CHECK(string{"lug"} == langcode_three_new(string{"lg"}));
    CHECK(string{"mac"} == langcode_three_new(string{"mk"}));
    CHECK(string{"mah"} == langcode_three_new(string{"mh"}));
    CHECK(string{"mal"} == langcode_three_new(string{"ml"}));
    CHECK(string{"mao"} == langcode_three_new(string{"mi"}));
    CHECK(string{"mar"} == langcode_three_new(string{"mr"}));
    CHECK(string{"may"} == langcode_three_new(string{"ms"}));
    CHECK(string{"mlg"} == langcode_three_new(string{"mg"}));
    CHECK(string{"mlt"} == langcode_three_new(string{"mt"}));
    CHECK(string{"mon"} == langcode_three_new(string{"mn"}));
    CHECK(string{"nau"} == langcode_three_new(string{"na"}));
    CHECK(string{"nav"} == langcode_three_new(string{"nv"}));
    CHECK(string{"nbl"} == langcode_three_new(string{"nr"}));
    CHECK(string{"nde"} == langcode_three_new(string{"nd"}));
    CHECK(string{"ndo"} == langcode_three_new(string{"ng"}));
    CHECK(string{"nep"} == langcode_three_new(string{"ne"}));
    CHECK(string{"nno"} == langcode_three_new(string{"nn"}));
    CHECK(string{"nob"} == langcode_three_new(string{"nb"}));
    CHECK(string{"nor"} == langcode_three_new(string{"no"}));
    CHECK(string{"nya"} == langcode_three_new(string{"ny"}));
    CHECK(string{"oci"} == langcode_three_new(string{"oc"}));
    CHECK(string{"oji"} == langcode_three_new(string{"oj"}));
    CHECK(string{"ori"} == langcode_three_new(string{"or"}));
    CHECK(string{"orm"} == langcode_three_new(string{"om"}));
    CHECK(string{"oss"} == langcode_three_new(string{"os"}));
    CHECK(string{"pan"} == langcode_three_new(string{"pa"}));
    CHECK(string{"per"} == langcode_three_new(string{"fa"}));
    CHECK(string{"pli"} == langcode_three_new(string{"pi"}));
    CHECK(string{"pol"} == langcode_three_new(string{"pl"}));
    CHECK(string{"por"} == langcode_three_new(string{"pt"}));
    CHECK(string{"pus"} == langcode_three_new(string{"ps"}));
    CHECK(string{"que"} == langcode_three_new(string{"qu"}));
    CHECK(string{"roh"} == langcode_three_new(string{"rm"}));
    CHECK(string{"rum"} == langcode_three_new(string{"ro"}));
    CHECK(string{"run"} == langcode_three_new(string{"rn"}));
    CHECK(string{"rus"} == langcode_three_new(string{"ru"}));
    CHECK(string{"sag"} == langcode_three_new(string{"sg"}));
    CHECK(string{"san"} == langcode_three_new(string{"sa"}));
    CHECK(string{"sin"} == langcode_three_new(string{"si"}));
    CHECK(string{"slo"} == langcode_three_new(string{"sk"}));
    CHECK(string{"slv"} == langcode_three_new(string{"sl"}));
    CHECK(string{"sme"} == langcode_three_new(string{"se"}));
    CHECK(string{"smo"} == langcode_three_new(string{"sm"}));
    CHECK(string{"sna"} == langcode_three_new(string{"sn"}));
    CHECK(string{"snd"} == langcode_three_new(string{"sd"}));
    CHECK(string{"som"} == langcode_three_new(string{"so"}));
    CHECK(string{"sot"} == langcode_three_new(string{"st"}));
    CHECK(string{"spa"} == langcode_three_new(string{"es"}));
    CHECK(string{"srd"} == langcode_three_new(string{"sc"}));
    CHECK(string{"srp"} == langcode_three_new(string{"sr"}));
    CHECK(string{"ssw"} == langcode_three_new(string{"ss"}));
    CHECK(string{"sun"} == langcode_three_new(string{"su"}));
    CHECK(string{"swa"} == langcode_three_new(string{"sw"}));
    CHECK(string{"swe"} == langcode_three_new(string{"sv"}));
    CHECK(string{"tah"} == langcode_three_new(string{"ty"}));
    CHECK(string{"tam"} == langcode_three_new(string{"ta"}));
    CHECK(string{"tat"} == langcode_three_new(string{"tt"}));
    CHECK(string{"tel"} == langcode_three_new(string{"te"}));
    CHECK(string{"tgk"} == langcode_three_new(string{"tg"}));
    CHECK(string{"tgl"} == langcode_three_new(string{"tl"}));
    CHECK(string{"tha"} == langcode_three_new(string{"th"}));
    CHECK(string{"tib"} == langcode_three_new(string{"bo"}));
    CHECK(string{"tir"} == langcode_three_new(string{"ti"}));
    CHECK(string{"ton"} == langcode_three_new(string{"to"}));
    CHECK(string{"tsn"} == langcode_three_new(string{"tn"}));
    CHECK(string{"tso"} == langcode_three_new(string{"ts"}));
    CHECK(string{"tuk"} == langcode_three_new(string{"tk"}));
    CHECK(string{"tur"} == langcode_three_new(string{"tr"}));
    CHECK(string{"twi"} == langcode_three_new(string{"tw"}));
    CHECK(string{"uig"} == langcode_three_new(string{"ug"}));
    CHECK(string{"ukr"} == langcode_three_new(string{"uk"}));
    CHECK(string{"urd"} == langcode_three_new(string{"ur"}));
    CHECK(string{"uzb"} == langcode_three_new(string{"uz"}));
    CHECK(string{"ven"} == langcode_three_new(string{"ve"}));
    CHECK(string{"vie"} == langcode_three_new(string{"vi"}));
    CHECK(string{"vol"} == langcode_three_new(string{"vo"}));
    CHECK(string{"wel"} == langcode_three_new(string{"cy"}));
    CHECK(string{"wln"} == langcode_three_new(string{"wa"}));
    CHECK(string{"wol"} == langcode_three_new(string{"wo"}));
    CHECK(string{"xho"} == langcode_three_new(string{"xh"}));
    CHECK(string{"yid"} == langcode_three_new(string{"yi"}));
    CHECK(string{"yor"} == langcode_three_new(string{"yo"}));
    CHECK(string{"zha"} == langcode_three_new(string{"za"}));
    CHECK(string{"zul"} == langcode_three_new(string{"zu"}));
}

static void test_lang_code_not_found_new() {
    CHECK(strcmp("bb", langcode_three_old("bb")) == 0);
    CHECK(strcmp("cc", langcode_three_old("cc")) == 0);
    CHECK(strcmp("dd", langcode_three_old("dd")) == 0);
    CHECK(strcmp("gg", langcode_three_old("gg")) == 0);
    CHECK(strcmp("hh", langcode_three_old("hh")) == 0);
    CHECK(strcmp("jj", langcode_three_old("jj")) == 0);
    CHECK(strcmp("ll", langcode_three_old("ll")) == 0);
    CHECK(strcmp("mm", langcode_three_old("mm")) == 0);
    CHECK(strcmp("oo", langcode_three_old("oo")) == 0);
    CHECK(strcmp("pp", langcode_three_old("pp")) == 0);
    CHECK(strcmp("qq", langcode_three_old("qq")) == 0);
    CHECK(strcmp("rr", langcode_three_old("rr")) == 0);
    CHECK(strcmp("uu", langcode_three_old("uu")) == 0);
    CHECK(strcmp("vv", langcode_three_old("vv")) == 0);
    CHECK(strcmp("ww", langcode_three_old("ww")) == 0);
    CHECK(strcmp("xx", langcode_three_old("xx")) == 0);
    CHECK(strcmp("yy", langcode_three_old("yy")) == 0);
    CHECK(strcmp("zz", langcode_three_old("zz")) == 0);
}

static void test_lang_code_str_not_found_new() {
    CHECK(langcode_three_old(string{"bb"}) == string{"bb"});
    CHECK(langcode_three_old(string{"cc"}) == string{"cc"});
    CHECK(langcode_three_old(string{"dd"}) == string{"dd"});
    CHECK(langcode_three_old(string{"gg"}) == string{"gg"});
    CHECK(langcode_three_old(string{"hh"}) == string{"hh"});
    CHECK(langcode_three_old(string{"jj"}) == string{"jj"});
    CHECK(langcode_three_old(string{"ll"}) == string{"ll"});
    CHECK(langcode_three_old(string{"mm"}) == string{"mm"});
    CHECK(langcode_three_old(string{"oo"}) == string{"oo"});
    CHECK(langcode_three_old(string{"pp"}) == string{"pp"});
    CHECK(langcode_three_old(string{"qq"}) == string{"qq"});
    CHECK(langcode_three_old(string{"rr"}) == string{"rr"});
    CHECK(langcode_three_old(string{"uu"}) == string{"uu"});
    CHECK(langcode_three_old(string{"vv"}) == string{"vv"});
    CHECK(langcode_three_old(string{"ww"}) == string{"ww"});
    CHECK(langcode_three_old(string{"xx"}) == string{"xx"});
    CHECK(langcode_three_old(string{"yy"}) == string{"yy"});
    CHECK(langcode_three_old(string{"zz"}) == string{"zz"});
}

#ifndef MAX_ITERATIONS
#define MAX_ITERATIONS 100 
#endif

void test(size_t max_iterations) {
#ifdef TEST_OLD
    printf("testing old API %zu times\n", size_t{max_iterations});
#else
    auto container = std::string{};
#if defined(USING_VECTOR)
    container = "vector<const char*>";
#elif defined(USING_VECTOR_SORTED)
    container = "vector<const char*> sorted";
#elif defined(USING_VECTOR_STR)
    container = "vector<string>";
#elif defined(USING_VECTOR_STR_SORTED)
    container = "vector<string> sorted";
#elif defined(USING_MAP)
    container = "map<const char*>";
#elif defined(USING_MAP_STR)
    container = "map<string>";
#elif defined(USING_DICT)
    container = "unordered_map<const char*>";
#elif defined(USING_DICT_STR)
    container = "unordered_map<string>";
#else
#error "not setupt to use any container"
#endif
    printf("testing new API using %s %zu times\n", container.c_str(), size_t{max_iterations});
#endif

    for (size_t i = 0; i < size_t{max_iterations}; ++i) {
#ifdef TEST_OLD
        test_lang_code_old();
        test_lang_code_str_old();
        test_lang_code_not_found_old();
        test_lang_code_str_not_found_old();
#else
        test_lang_code_new();
        test_lang_code_str_new();
        test_lang_code_not_found_new();
        test_lang_code_str_not_found_new();
#endif
    }
}

int main(int argc, char*argv[]) {
    size_t max_iterations = MAX_ITERATIONS;

    if (argc == 2) {
        max_iterations = std::stoull(argv[1]);
    }

    try {
        test(max_iterations);
    } catch (const std::exception& ex) {
        std::cout << "ERROR: " << ex.what() << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}

